### ISSUE TITLE
2048 game using js

### ISSUE THREAD

**Issue by Git0Chetan** [shishirkhatiwada/100-js-projects#22]
I want to add 2048 game which is build using html ,css and javascript.

**Comment by shishirkhatiwada** [comment]
Sure, I can help you add the 2048 game to your GitHub repository. Please provide me with the project files, and I'll guide you through the process

**Comment by Git0Chetan** [comment]
I want to contribute on the project.
is these Repository Participating in Hactoberfest.
because I can't see the labels on any PR which are closed in the past.

**Comment by shishirkhatiwada** [comment]
yes it is participating in hacktoberfest
