### ISSUE TITLE
add the tic-tac-toe game

### ISSUE THREAD

**Issue by 0nikhilkumar** [shishirkhatiwada/100-js-projects#7]
please add the tic tac toe game with the help of HTML/CSS/JS

**Comment by 0nikhilkumar** [comment]
As I am hacktoberfest'23 participant please review it and merge it and give the label of "hacktoberfest-accepted" @shishirkhatiwada 

Note :- please mark the label of "hacktoberfest-accepted"

**Comment by shishirkhatiwada** [comment]
done
